//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "namespaces")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub active: bool,
    #[sea_orm(unique)]
    pub client_id: Uuid,
    #[sea_orm(unique)]
    pub client_secret: Uuid,
    pub environment_type: String,
    pub service_name: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::errors::Entity")]
    Errors,
    #[sea_orm(has_many = "super::user_namespace_junction::Entity")]
    UserNamespaceJunction,
}

impl Related<super::errors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Errors.def()
    }
}

impl Related<super::user_namespace_junction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserNamespaceJunction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
