//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::errors::Entity as Errors;
pub use super::namespaces::Entity as Namespaces;
pub use super::refresh_tokens::Entity as RefreshTokens;
pub use super::user_namespace_junction::Entity as UserNamespaceJunction;
pub use super::users::Entity as Users;
